{"name":"WHO SDG Indicator 1","description":"","version":"1.0","culture":"en-US","modifiedTime":"2022-06-04T08:31:44.8374886+00:00","pbi:mashup":{"fastCombine":false,"allowNativeQueries":false,"queriesMetadata":{"Indicators data fx":{"queryId":"6bd1f374-b264-4d63-a80b-273aeb133e68","queryName":"Indicators data fx"},"Indicators":{"queryId":"a8138a8e-028a-44ca-b710-3501ead5e328","queryName":"Indicators","loadEnabled":true}},"document":"section Section1;\r\nshared #\"Indicators data fx\" = (indicatorCode as text) =>\n\nlet\n\nfxPaging = (pageNumber as number) =>\n    let\n        Source = Json.Document(\n            Web.Contents(\n                \"https://unstats.un.org/SDGAPI/v1/\",\n                [\n                    RelativePath = \"sdg/Indicator/Data\",\n                    Query = \n                        [\n                            indicator = indicatorCode,\n                            pageSize = \"500\",\n                            page= Number.ToText(pageNumber)\n                        ]\n                ]\n            )\n        ),\n        data = Source[data],\n        #\"Converted to Table\" = Table.FromList(data, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\n        #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", \n            {\"seriesDescription\", \"geoAreaName\", \"value\", \"valueType\",\"timePeriodStart\",\"attributes\",\"geoAreaCode\"}, \n            {\"seriesDescription\", \"geoAreaName\", \"value\", \"valueType\",\"timePeriodStart\",\"attributes\",\"geoAreaCode\"})\n    in\n        #\"Expanded Column1\",\n\n\n    Source = Json.Document(Web.Contents(\n        \"https://unstats.un.org/SDGAPI/v1/\",\n        [\n            RelativePath = \"sdg/Indicator/Data\",\n            Query = \n                [\n                    indicator = indicatorCode,\n                    pageSize = \"500\"\n                ]\n        ]\n    )),\n    totalPages = Source[totalPages],\n    pageList= {1..totalPages},\n    #\"Converted to Table\" = Table.FromList(pageList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\n    applyFunction = Table.AddColumn(#\"Converted to Table\", \"Function\", each fxPaging([Column1]))\n\n\n\nin \n\napplyFunction;\r\nshared Indicators = let\r\n  Source = Json.Document(Web.Contents(\n        \"https://unstats.un.org/SDGAPI/v1/\",\n        [\n            RelativePath = \"sdg/Indicator/List\"\n        ]\n    )),\r\n  #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),\r\n  #\"Expanded Column1\" = Table.ExpandRecordColumn(#\"Converted to Table\", \"Column1\", {\"goal\", \"target\", \"code\", \"description\", \"tier\", \"uri\"}, {\"Goal\", \"Tagert\", \"Indicator\", \"Indicator description\", \"Tier\", \"Uri\"}),\r\n  #\"Invoked Custom Function\" = Table.AddColumn(#\"Expanded Column1\", \"Indicators data fx\", each #\"Indicators data fx\"([Indicator])),\r\n  #\"Expanded Indicators data fx\" = Table.ExpandTableColumn(#\"Invoked Custom Function\", \"Indicators data fx\", {\"Function\"}, {\"Function\"}),\r\n  #\"Expanded Function\" = Table.ExpandTableColumn(#\"Expanded Indicators data fx\", \"Function\", {\"seriesDescription\", \"geoAreaName\", \"value\", \"valueType\", \"timePeriodStart\", \"attributes\", \"geoAreaCode\"}, {\"Series description\", \"Geo name\", \"Value\", \"Value type\", \"Year\", \"attributes\", \"Geo code\"}),\r\n  #\"Expanded attributes\" = Table.ExpandRecordColumn(#\"Expanded Function\", \"attributes\", {\"Units\"}, {\"Units\"}),\r\n  #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Expanded attributes\", {\"Value\"}),\r\n  #\"Transform columns\" = Table.TransformColumnTypes(#\"Removed Errors\", {{\"Goal\", type text}, {\"Tagert\", type text}, {\"Indicator\", type text}, {\"Indicator description\", type text}, {\"Tier\", type text}, {\"Uri\", type text}, {\"Series description\", type text}, {\"Geo name\", type text}, {\"Value\", type text}, {\"Value type\", type text}, {\"Year\", type text}, {\"Units\", type text}, {\"Geo code\", type text}}),\r\n  #\"Replace errors\" = Table.ReplaceErrorValues(#\"Transform columns\", {{\"Goal\", null}, {\"Tagert\", null}, {\"Indicator\", null}, {\"Indicator description\", null}, {\"Tier\", null}, {\"Uri\", null}, {\"Series description\", null}, {\"Geo name\", null}, {\"Value\", null}, {\"Value type\", null}, {\"Year\", null}, {\"Units\", null}, {\"Geo code\", null}})\r\nin\r\n  #\"Replace errors\";\r\n"},"annotations":[{"name":"pbi:QueryGroups","value":"[]"}],"entities":[{"$type":"LocalEntity","name":"Indicators","description":"","pbi:refreshPolicy":{"$type":"FullRefreshPolicy","location":"Indicators.csv"},"attributes":[{"name":"Goal","dataType":"string"},{"name":"Tagert","dataType":"string"},{"name":"Indicator","dataType":"string"},{"name":"Indicator description","dataType":"string"},{"name":"Tier","dataType":"string"},{"name":"Uri","dataType":"string"},{"name":"Series description","dataType":"string"},{"name":"Geo name","dataType":"string"},{"name":"Value","dataType":"string"},{"name":"Value type","dataType":"string"},{"name":"Year","dataType":"string"},{"name":"Units","dataType":"string"},{"name":"Geo code","dataType":"string"}],"partitions":[{"name":"FullRefreshPolicyPartition","refreshTime":"2022-06-04T12:51:20.5630498+00:00","location":"https://wabiswiznpcdsap1.blob.core.windows.net:443/221816fd-fc5f-4550-b7f6-acd6cd00af38/Indicators.csv?snapshot=2022-06-04T12%3A51%3A20.5437788Z"}]}]}